### ISSUE TITLE
Possibility to make headlessUncompress to respect either the given inlength or the num 

### ISSUE THREAD

**Issue by TuomasKiviaho** [lemire/JavaFastPFOR#37]
Could headlessUncompress be made to respect optionally the given input length instead of having to know the number of compressed values beforehand.

I have seen the {{ignored by some schemes}} claim in the javadoc and I've seen https://github.com/lemire/JavaFastPFOR/issues/35 
and https://github.com/lemire/JavaFastPFOR/blob/master/example.java#L88-L146 how the codecs are supposed to be used. Still by looking at the implementation of both BinaryPacking and VariableByte, I wonder if this behavior is could be explicitly documented on these codecs so that one doesn't have to take a peek into the code or alternatively face an ArrayIndexOutOfBounds exception as I did.

I'd like to have a variant where inlength is respected and output buffer could overflow (this could be simply deduced from either inlength or num being given as negative value) so that I don't have to separately "store the number of compressed values elsewhere" as suggested. I guess supporting both of the given lengths would require extra instructions in most cases.

**Comment by lemire** [comment]
I'm sure the JavaDoc can and should be improved, but I'd like to better understand the issue. 

If you do not track elsewhere the number of compressed values, then you should not be calling headlessUncompress/headlessCompress. This part of the API was added for people who track the number of compressed values and do not want the CODECs to do it.

If you do not want to track elsewhere the number of compressed values, then you should be calling uncompress/compress.

Maybe the JavaDoc isn't sufficiently clear on this point? If so, then it should be fixed indeed.

As for your comment suggesting that you should be able to call headlessUncompress without knowing the number of compressed values... the answer is a clear no in general... the point of even having this API is to build on the assumption that the user knows (somehow) the number of compressed values. We have another API (uncompress/compress) when the users do not have this information. 

We absolutely rely in the user deciding whether he knows the number of compressed values and choosing the appropriate API. 

It is a bit more complicated than it might be, but we support various use cases.

**Comment by lemire** [comment]
Ok. So I have looked at the JavaDoc... we have the standard interface... ``IntegerCODEC``... I guess this interface is not a problem...

http://static.javadoc.io/me.lemire.integercompression/JavaFastPFOR/0.1.10/me/lemire/integercompression/IntegerCODEC.html

Then we have ``SkippableIntegerCODEC``...

http://static.javadoc.io/me.lemire.integercompression/JavaFastPFOR/0.1.10/me/lemire/integercompression/SkippableIntegerCODEC.html

The JavaDoc says...

> Interface describing a standard CODEC to compress integers. This is a variation on the IntegerCODEC interface meant to be used for random access. The main difference is that we must specify the number of integers we wish to decode. This information should be stored elsewhere. This interface was designed by the Terrier team for their search engine.

You write: "Could headlessUncompress be made to respect optionally the given input length instead of having to know the number of compressed values beforehand." I think that the answer is that you should be using the ``IntegerCODEC`` interface which was designed for this purpose. 

It looks to me like the JavaDoc is relatively clear. Of course, if you have suggestions, they are welcome.

Maybe, also, you wish for a third interface type, besides ``IntegerCODEC`` and ``SkippableIntegerCODEC``. Contributions in this respect are invited. Meanwhile, my feeling is that we cover a wide range of use cases with the two interfaces we already offer.

So I am going to close this. Reopen if you disagree.
